### ISSUE TITLE
Relase 1.4.2 to Cocoapods?

### ISSUE THREAD

**Issue by Bobbyphtr** [bookingcom/perfsuite-ios#14]
Is there any plan to release the PerformanceSuite to 1.4.2 ? 

it looks like the podspec is not updated yet on the main thrunk.
https://github.com/CocoaPods/Specs/blob/master/Specs/f/d/e/PerformanceSuite/1.2.5/PerformanceSuite.podspec.json

I plan on using the dependency by mentioning it in my `Podspec`

```
s.dependency "PerformanceSuite", "=1.4.2"
```

But sadly cocoapods can't find the version.
My current workaround is to add your podspec to our own Specs trunk so Cocoapods can do a look-up from there.

**Comment by Bobbyphtr** [comment]
Background: 
When using version `1.2.5`, This assertion is always being triggered.
```
assert(viewController == self.viewController)
```
It looks like the issue has been fixed on this commit
https://github.com/bookingcom/perfsuite-ios/commit/9103eb088ee95d5262d2b992897f0603c410f968

It is a blocking error on development, so I encourage this to be released.

**Comment by pilot34** [comment]
Sorry for the late reply.

We [stopped releasing podspecs](https://github.com/bookingcom/perfsuite-ios/commit/2263dc82c44829181d8f0559cfa9d6e4acd593b5) to CocoaPods repo, as it became quite unreliable. After CocoaPods [went into the maintenance mode](https://blog.cocoapods.org/CocoaPods-Support-Plans/) I do not expect them to fix anything. So I advise to include the spec with the link to Github repo

something like:
```
pod 'PerformanceSuite', :git => 'https://github.com/bookingcom/perfsuite-ios.git', :tag => '1.4.2'
```

**Comment by pilot34** [comment]
I will close this issue, feel free to open the new issue for the source problem (assert), if it still appears in the latest version.
