### ISSUE TITLE
Name collision enum and module name

### ISSUE THREAD

**Issue by kkivan** [bookingcom/perfsuite-ios#2]
Seems that there is a collision between module PerformanceSuite and enum PerformanceSuite.

<img width="1238" alt="image" src="https://github.com/bookingcom/perfsuite-ios/assets/11199580/a533c9d8-9d72-4bfe-9866-1675f0154872">

Personally, I try to avoid having a type with the same name as the module.

**Comment by pilot34** [comment]
Thx for reporting! 

Naming is hard. I renamed enum to `PerformanceMonitoring` in release [1.1.0](https://github.com/bookingcom/perfsuite-ios/releases/tag/1.1.0).

Please check if it works.
