### ISSUE TITLE
SwiftPM Fails to Compile (Intel)

### ISSUE THREAD

**Issue by Sherlouk** [bookingcom/perfsuite-ios#3]
Hey 👋 

Looks like [the most recent release](https://github.com/bookingcom/perfsuite-ios/releases/tag/1.2.4) and [recent commits directly on `main`](https://github.com/bookingcom/perfsuite-ios/commit/826a8d4eabe66f8743faf252a6fbad15f4d97340) are trying to resolve this issue but thought I'd open an issue to track progress.

I've tried building both from `main` and from the latest release, and on my Intel Mac is still unable to compile with the following error:

<img width="1408" alt="Screenshot 2023-12-01 at 1 17 16 pm" src="https://github.com/bookingcom/perfsuite-ios/assets/15193942/413412c3-3426-4838-b861-feb4a00e03a0">

> Expected function body after function declarator

The in turn causes a "Could not build Objective-C module 'MainThreadCallStack'" error on the import in HangInfo.

This is using Xcode 15.0.1, building to an iOS 17.0.1 simulator.

**Comment by pilot34** [comment]
Oh, thx for the fix. I was in the middle of fixing and forgot about that 🤦‍♂️Let me verify merge and create a new release

**Comment by pilot34** [comment]
I've published the release `1.2.5` with your fix. Please close the issue if it works.

I would like also to chat about your use case for using our PerformanceSuite. Pinged you in Mastodon.

**Comment by Sherlouk** [comment]
Apologies @pilot34, I clearly forgot to reply to this message - but absolutely the tag above did fix the problem. Sorry for the slow resposne.
